COMPOSE_PROFILES=local

POSTGRES_USER: admin
POSTGRES_PASSWORD: root
POSTGRES_DB: postgres
PGDATA: /var/lib/postgresql/data/pgdata


PGADMIN_DEFAULT_EMAIL: admin@admin.com
PGADMIN_DEFAULT_PASSWORD: root

OPTUNA_DB_USER: optunauser
OPTUNA_DB_PASSWORD: optunapassword

MINIO_ROOT_USER: ukjwf5mzmFJ2An00HCMC
MINIO_ROOT_PASSWORD: xDUoCBXUODriX40nCZmJIVnjtwgdnMA8UCuOfTY1
MINIO_DEFAULT_BUCKETS: mlflow

MLFLOW_DB_USER: mlflowuser
MLFLOW_DB_PASSWORD: test
AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
S3_ENDPOINT_URL=http://minio:9000
MLFLOW_S3_IGNORE_TLS=true