COMPOSE_PROFILES=local

POSTGRES_USER: admin
POSTGRES_PASSWORD: root
POSTGRES_DB: postgres
PGDATA: /var/lib/postgresql/data/pgdata


PGADMIN_DEFAULT_EMAIL: admin@admin.com
PGADMIN_DEFAULT_PASSWORD: root

MLFLOW_DB_USER: mlflowuser
MLFLOW_DB_PASSWORD: test

OPTUNA_DB_USER: optunauser
OPTUNA_DB_PASSWORD: optunapassword

MINIO_ROOT_USER: ukjwf5mzmFJ2An00HCMC
MINIO_ROOT_PASSWORD: xDUoCBXUODriX40nCZmJIVnjtwgdnMA8UCuOfTY1
MINIO_DEFAULT_BUCKETS: mlflow
