sources:
  apartments:
    source: https://www.kaggle.com/code/krzysztofjamroz/apartment-for-sale-in-poland-data-analysis/input
    target: price
    parametrized_columns: ['ownership']
    exclude_columns: ['ownership']
    include_only_columns: